.travis.yml

This will prevent to deploy the application with a production configuration when merging back from master to staging after a release.
Note:
- A tag causes the application to load the production configuration

chore: Only allow tag deployments on master

---

.github/workflows/test_build_deploy.yml

This is a port from the webapp repository, since that part of logic is the same.
*originating from: https://github.com/wireapp/wire-webapp/pull/11242*

chore: Add link to explain why Helm chart update job might throw an error

---

src/script/component/OpenWireButtons.tsx
src/script/page/ConversationJoin.tsx

----
----
Fixes extra parameters that were added to all the generated urls since #3483

runfix: Do not automatically add extra url params to wire links [SQSERVICES-1428, SQSERVICES-1415]

---

src/script/Root.tsx
src/script/module/action/AccountAction.ts
src/script/page/ConversationJoin.tsx
src/script/util/urlUtil.ts

----
----
Add hl=(lang) param to url based on user's navigator preferences.
----
----
----
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

fix: add hl param to url based on user's navigator

---

src/script/page/ConversationJoin.tsx

Temporary guest join is completely handled on the webapp side now, no need to add this action button here anymore

fix: Remove the join as temporary guest link from conversation join

---

.github/workflows/cherry-pick-release-to-dev.yml
.github/workflows/ci.yml
.github/workflows/test_build_deploy.yml

----
----
Adds some new pipeline stuff for release

chore: update release pipeline

---

server/package.json
server/yarn.lock

Reverts wireapp/wire-account#4466

Revert "chore: Bump prettier from 2.8.8 to 3.2.4 in /server"

---

.github/workflows/test_build_deploy.yml

This will allow tagged commits with the pattern `q1-2024` to be pushed to the `wire-builds` repo

chore: Publish q1-2024 tags to wire-builds

---

.github/workflows/test_build_deploy.yml

Similar to https://github.com/wireapp/wire-webapp/pull/17311

ci: production releases go to 'main' in wire-builds

---

.github/workflows/deploy-to-test-env.yml
.github/workflows/generate-changelog.yml
.github/workflows/test_build_deploy.yml

----
----
This PR fixes a potential command injection in the GitHub Actions workflow of this repository.
Unsanitized user input could be used to execute arbitrary code in the context of the workflow.
e.g.:
- specially crafted tags, e.g. `docker/v0.0.0;$(cat${IFS}/etc/passwd)#`,
- workflow inputs like `env`
Instead of using the unsanitized tag directly, it is passed to the run step as an environment variable. This prevents command execution like in the above example.
This change was tested with the workflow listed below in a separate repository by pushing tags in the shape of 'docker/v0.0.0;$(cat${IFS}/etc/passwd)#'.
Test0 resembles the original workflow of this repo, and Test1 is the fixed version.
An actual test can be made by pushing above tag …

fix(actions): prevent command injection (WPB-9709)

---

babel.config.js
package.json
yarn.lock

When updating packages, I've removed babel-preset-css-prop. It's needed when we overwrite ui-kit library's styles and want them to be extended instead of overwritten completely. It was causing issues like this:
See margin being applied, but all other styles are reset.
```jsx
<ButtonLink href={`${WEBAPP_URL}/auth`} css={{marginTop: 40}} data-uie-name="do-go-back-to-login">
{t('login')}
</ButtonLink>
```
without preset:
now, with preset:

runfix: put css-prop babel preset back

---

src/i18n/en-US.json
src/script/page/PasswordForgot.tsx

Removes "email not in use" error message when trying to reset password with an email that doesn't exist. For now it'll show generic "Something went wrong" error. After the request is handled properly on BE side (to always return 200 OK), it will always show the success screen, even for non-existing emails.
Before:
Now:

fix: don't expose email already in use [WPB-9752]

---

babel.config.js

`'@emotion/babel-preset-css-prop'` needs to be put before preset-react. In a previous config react fragments (`<></>`) were not supported without explicitly importing react.

runfix: order of babel presets to support react fragments

---

.github/workflows/test_build_deploy.yml

----
----
The `test_build_deploy` workflow fails for `staging`.
For the `staging` branch we don't have a `targets` configuration available, thus the workflow step tries to parse an empty string as a JSON object.
Setting `targets` to an empty list literal `[]` as a default (matching `.*`) should solve the issue. 
Merge this branch and observe the result of the workflow run for `staging`.
----
----
----
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

fix(actions): prevent workflow error when no target environment is available in wire-build - WPB-6801

---

src/i18n/de-DE.json

Updated DE translation for 'Reset password'.
Removed 'description' from the file to allow Product team to add translation using Crowdin.

fix: updated DE translation for reset password [WPB-10981]

---

.github/workflows/test_build_deploy.yml

Updated node version to 20 test_build_deploy GH action.
https://github.com/actions/runner-images/issues/7002
https://github.com/wireapp/wire-account/actions/runs/11037520154/job/30658572702

chore: update node version (20) for test_build_deploy

---

.github/workflows/test_build_deploy.yml

The branch name and tags used to map the correct account release to wire-build was based on the name of webapp branches and does not correspond to the account repo.
- map the `main` wire-account branch to the `main` wire-build branch (previously was mapping a `production` tag that doesn't exist on wire-account)
- map the `staging` wire-account branch to the `dev` wire-build branch (wira-account `staging` branch is used in dev environments and not with production backends)

chore: map correct branch to wire-builds

---

package.json
src/i18n/en-US.json
src/script/module/action/TeamAction.ts
src/script/page/migration/TermsAcknowledgement.tsx
src/script/page/migration/styles.ts
yarn.lock

Added inviter's email on terms acceptance page and updated warning box color.
https://www.figma.com/design/udW2CnykWhQp4IBh72JpdS/Individual-to-Team?node-id=12-619&node-type=canvas&t=7zBVRCSfQoKxnKXs-0

feat(team-invitation): add inviter email in terms acceptance page [WPB-12142]

---

src/script/page/migration/styles.ts

Updated migration page font color

fix: update migration pages font color [WPB-14460]

---

package.json
server/Server.ts
server/ServerConfig.ts
server/config.ts
server/templates/index.hbs
src/script/Environment.ts
src/script/Root.tsx
src/script/page/migration/AcceptInvitation.tsx
src/script/page/migration/ConfirmInvitation.tsx
src/script/page/migration/TermsAcknowledgement.tsx
src/script/page/migration/Welcome.tsx
src/script/util/Tracking/Tracking.ts
src/script/util/Tracking/constants.ts
src/script/util/Tracking/types.ts
yarn.lock

Added countly events tracking for (Ind -> Team user) migration flow.

feat: add countly event tracking for migration flow [WPB-11317]

---

src/script/page/migration/styles.ts

Adjust font-size for user migration pages

fix: fixed font-size for user migration pages

---

.github/workflows/test_build_deploy.yml

node 22 environments need a bit longer time to start so we need to wait for deployment
Node.js 22 environments:
Have longer initialization or more strict validation
App version registration is asynchronous in AWS — it might not be “ready” when deployment starts

chore: fix deployment race condition

---

.elasticbeanstalk/config.yml
.github/workflows/test_build_deploy.yml
README.md

**PR Summary**
Update Account app deployment to the new Node.js 22 Elastic Beanstalk environments
**What’s changed**
Point staging and main deploy steps at the *-node22 EB environments running Node 22

(chore): Change pipeline to deploy to node22 environments

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test_build_deploy.yml

- `gha-yarn-cache` is no longer supported

ci: remove gha-yarn-cache from github workflows
