package.json
yarn.lock

Reverts wireapp/wire-account#586

build(deps): Downgrade react-router from 5.0.1 to 5.0.0

---

package.json
src/script/module/action/index.tsx
yarn.lock

chore: Update and migrate to @wireapp/api-client v9.1.4

---

package.json
yarn.lock

Reverts wireapp/wire-account#1090

Revert "build(deps-dev): Bump @types/react-router-dom from 4.3.5 to 5.1.3"

---

package.json

See https://github.com/okonet/lint-staged#v10

chore: Remove "git add" from lint-staged scripts

---

server/yarn.lock

https://github.com/Unitech/pm2/issues/4937

chore: Update Axios in pm2

---

bin/push_docker.js

This change set is a result and integration of the changes introduced in
https://github.com/wireapp/wire-webapp/pull/11022 - mainly to standardize
and to adhere to the convention introduced here.

chore: Change docker tag name scheme

---

.github/workflows/test_build_deploy.yml

This change set is the effort to port the changes introduced in
https://github.com/wireapp/wire-webapp/pull/11158. It is meant to
keep the version up to date in our deployment configuration.

chore: CI Add job to update image tag in corresponding Helm chart

---

bin/push_docker.js

The container image tag information are now solely defined by the script input.
Due to the fact that branch information are not available during the release
process (because it indicated by a tag), it make sense to rather base the tag
determination on the `stageParam`, which is set i the respective pipeline step.
This also allows to further simplify the script assembling that tag and pushing
the images. Alongside, some variables have been renamed to clarify the meaning
of their values.
The pipelines uses 7 characters while the script only used 6 (second param of
substring behaves exclusive). This has been aligned.
*Owner: @arianvp*

chore: Base tag information on script input rather than branch name

---

src/i18n/en-US.json
src/script/component/OpenWireButtons.tsx
src/script/page/ConversationJoin.tsx

runfix: Show cannot join message on mobile browser [FS-497]

---

src/i18n/en-US.json

----
----
_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._
_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._
_Briefly describe the solutions you have implemented for the issues explained above._
_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._
Needs releases with:
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._
_Specify here any other facts that you think are important for this issue._
_Attachments like images, videos, …

fix: Update join-conversation copies

---

.github/workflows/deploy-to-test-env.yml

----
----
Adds a manual pipeline to easily deploy changes for aws migration, without first merging these changes to staging or prod.

feat: add manual deploy pipeline to prepare for aws migration

---

src/i18n/en-US.json

Changed Login to Log in requested by translation team

chore: update translation (WPB-3157)

---

src/i18n/en-US.json
src/script/component/DirectDownloadButton.tsx
src/script/page/ConversationJoin.tsx

fix: Improve conversation join page copies

---

package.json
yarn.lock

----
----
updates the api version for a security dependency update.

chore(sec): update api client

---

charts/account-pages/values.yaml

Updates the helm chart values to support Kubernetes v1.28 and higher

runfix: assign a user and group id to containers

---

package.json
server/package.json
server/yarn.lock
yarn.lock

Upgrade all @wireapp dependencies that were upgraded within this ticket [WPB-7240](https://wearezeta.atlassian.net/browse/WPB-7240)
[WPB-7240]: https://wearezeta.atlassian.net/browse/WPB-7240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Update all @wireapp dependencies WPB-7240

---

webpack.config.dev.js

webpack hot reload was missing

chore: add hot-reload

---

app-config/package.json

Bumped web-app-config versions

chore: bump web-app-config versions [WPB-10832]

---

Dockerfile
server/package.json

Update node versions in Dockerfile and package.json similar to webapp

chore: update node versions in Dockerfile and package.json

---

.github/workflows/test_build_deploy.yml
Dockerfile
server/package.json
yarn.lock

revert attempt to roll back to node 18, we decided to update the node version on AWS

chore: revert attempt to roll back to node 18

---

.elasticbeanstalk/config.yml
.github/workflows/test_build_deploy.yml

Update to the pipeline to automatically deploy to the newest EB environments

chore: deploy staging and prod to new environments [WPB-11652]

---

src/i18n/en-US.json

Address a few suggestion from the localization team for strings related to personal user migration to team

chore: address copy review for migration to team

---

src/script/util/urlUtil.ts

Updated param for team migration from `team_code` to `team-code`

fix: updated team-code param as per BE request

---

src/i18n/en-US.json
src/script/page/migration/AcceptInvitation.tsx

Fixed error translation for migration page

fix: translation fix for migration pages

---

src/script/page/migration/styles.ts

Removed hard coded disabled button style.

fix: remove custom disabled button style

---

src/script/page/migration/ConfirmInvitation.tsx
src/script/page/migration/TermsAcknowledgement.tsx
src/script/page/migration/styles.ts

Fixed UI issues from play test feedback
https://github.com/user-attachments/assets/d49646ff-c4cf-4931-9398-9f50be263be7

fix: user migration play test feedback issues [WPB-14770]

---

src/i18n/en-US.json
src/script/page/migration/AcceptInvitation.tsx

Fixes the issue where login button text was incorrect and same thing for password input field.

fix: add missing translations for login button and password input [WPB-15471]

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test_build_deploy.yml
src/script/page/UserProfile.tsx

support for profiles with domains compatible with mobile platforms

feat: Add support for profile domain (WPB-10532)
